---
title: "Voting for a party and contributing to a party's vote. A unified account with Bayes' rule"
author:
  - name: Armin Schäfer
    affiliation:
      - id: jgu
        name: Johannes Gutenberg University
    orcid: 0000-0002-2538-0092
    email: schaefer@politik.uni-mainz.de
format: 
  html:
    number-sections: true
    code-fold: true
    code-summary: "Show the code"
    self-contained: true
    toc: true
highlight-style: tango
execute:
  warning: false
  message: false
bibliography: literature.bib
---

```{r}
#| label: setup
#| echo: false
#| message: false
#| warning: false

if (!require("pacman")) {
  install.packages("pacman")
  library(pacman)
}

p_load(here, tibble, patchwork, modelsummary, marginaleffects, gt, tidyverse)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  dplyr.summarise.inform = FALSE
)

my_theme <- function(...) {
  theme(
    plot.title = element_text(
      color = "black",
      size = 12,
      face = "bold"
    ),
    axis.text = element_text(
      color = "black",
      size = 10
    ),
    axis.title = element_text(
      color = "black",
      face = "bold",
      size = 10
    ),
    panel.grid.minor = element_blank(),
    strip.background = element_rect(
      fill = "white",
      color = "grey70"
    ),
    strip.text = element_text(color = "black"),
    legend.key.size = unit(0.3, "cm")
  )
}

df <- readRDS(here("data", "ess_short_incl11.rds"))

dfgreen <- df %>%
  filter(Green_sample == 1 & agea_clean > 24)


dfradicalright <- df %>%
  filter(RR_sample == 1 & agea_clean > 24)

```

# Introduction

The literature on political cleavages is interested in how strongly social groups are tied to political parties. For example, scholars ask whether left-wing parties are still the parties of the working class, whether the radical right is the party of older cohorts, and whether women are the core voters of the New Left. But asking these questions can mean two different things: First, one wants to know whether certain groups vote disproportionately for certain parties. Second, we also want to answer the reverse question, which is how much of the total vote for a party comes from a particular social group. It may well be that a group votes disproportionately for a party, but that the party still receives a small share of its votes from that particular group---especially if the group is small or turns out at lower rates than other groups. Hence, to understand cleavages, we need to look at voting patterns of social groups and at the contribution to a party's vote share.

Over decades, authors have suggested different ways to measure these two elements of cleavage politics. For example, @Alford.1962 introduced the *index of class voting* (ICV) to measure how much more likely workers than non-workers are to vote for left parties, whereas @Axelrod.1972 proposed the *contribution index* to capture the contribution of various groups to party electorates in the US. More recently, @Hooghe.2025 introduced the *Party Cleavage Index* (PCI) to measure the relative size of different voter groups in a party's electorate.

In this short note I will show that these different measures can all be expressed using Bayes' rule, although none of the authors mention it. I will first introduce Bayes' rule and then show how it can be used to calculate Alford's ICV, Axelrod's Contribution Index (ACI) and Hooghe and Marks' PCI. Using Bayes' rule has the advantage that we can easily move back and forth between a group's 'loyalty' (relative vote shares) and that group's 'contribution' to a party's total votes, which are but two sides of the same coin. In the second part of this note I will then gradually move to a more Bayesian way of calculating loyalty and contribution, which more clearly expresses the uncertainty of the estimates.

# A brief summary of Bayes' rule

Bayes' rule is a simple formula that allows us to calculate the probability of an event given that another event has occurred. Thus, it focuses on the conditional probability of event A given event B. @tbl-notation concentrates on 'two events' that can occur together or seperately. The joint probability of being a worker and voting for a Left party can be expressed as $Pr(A \cap B)$. The marginal probability of being a worker is $Pr(B)$ and the marginal probability of voting for a Left party is $Pr(A)$. The conditional probability of voting for a Left party given that one is a worker is $Pr(A | B)$. It is the share of all workers who vote for a Left party, and thus $Pr(A \cap B)$ divided by $Pr(B)$.

|                  | Left Party (A)   | Other Party (\~A)  |    Sum    |
|:---------------- |:----------------:|:------------------:|:-----------:|
| Worker (B)       |  Pr(A $\cap$ B)  |  Pr(\~A $\cap$ B)  |  **Pr(B)**  |
| Non-worker (\~B) | Pr(A $\cap$ \~B) | Pr(\~A $\cap$ \~B) | **Pr(\~B)** |
| Sum              |    **Pr(A)**     |    **Pr(\~A)**     |    Pr(U)    |

: Workers and Left vote. {#tbl-notation}

We can thus move back and forth between the conditional and the joint probability by rewriting the following formula:

The conditional probability of A given B is 

$$
Pr(A | B) = \frac{Pr(A \cap B)}{Pr(B)}
$$ {#eq-cond_a_b}


@eq-cond_a_b can be rewritten as the joint probabililty of A and B as 

$$
Pr(A \cap B) = Pr(A | B) \times Pr(B)
$$ {#eq-joint_a_b}

Since the joint probability of B and A is $Pr(B \cap A)$, we can also write 

$$
Pr(B \cap A) = Pr(B | A) \times Pr(A)
$$ {#eq-joint_b_a}

Finally, we can equate @eq-joint_a_b and @eq-joint_b_a: The joint probability of being a worker and voting left is the same as voting left and being a worker. This is the first step to derive Bayes' rule.

$$
Pr(A | B) \times Pr(B) = Pr(B | A) \times Pr(A)
$$ {#eq-equating}

The second step is to divide both sides by $Pr(B)$ to get the formula for Bayes' rule: 

$$
Pr(A | B) = \frac{Pr(B | A) \times Pr(A)}{Pr(B)}
$$ {#eq-bayes1} 

Obviously, we can also solve @eq-equating for the 'inverse probability' of being a worker given that one voted for the Left party: 

$$
Pr(B | A) = \frac{Pr(A | B) \times Pr(B)}{Pr(A)}
$$ {#eq-bayes2}

The elegant element of using Bayes' rule is that @eq-bayes1 is what @Hooghe.2025 call the "voter perspective" and @eq-bayes2 is the "party perspective", or, in Axelrod's [-@Axelrod.1972] term, the "contribution" of social group to a party's vote. The probability of a group voting for a party and the contribution of a group to a party's total vote are two sides of the same coin. But they are not the same thing.

# Measuring Loyality and Contribution

## The Alford Index

The Alford index, introduced in the 1960s, has been widely used to measure whether social democratic or centre-left parties are still the parties of the working class. Indeed, many studies claiming that class voting had ended use this simple measure: A decline in the Alford Index was taken as a sign that class had ceased to be a useful category for analysing voting behaviour [@Inglehart.1986: 463; @Clark.1991: 403; @Dalton.2002: 152; @Gingrich.2015: 57]. In highly individualised and pluralist societies, class voting was declared 'dead' [@Clark.2001].^[More complex approaches come to more nuanced and in part conflicting results [e.g. @Evans.2000; @vanderWaal.2007; @Hout.2010], but that is not our main concern here.]

Alford's *index of class voting* is calculated as the conditional probability to vote for the Left, given that your are a worker, minus the probability of a Left vote given that you are not a worker [@Alford.1962: 422]:^[The "~" symbol means "not".]

$$
Pr(Left | Worker) - Pr(Left | \mathord{\sim}Worker)
$$ {#eq-alford1}

To apply the formula more generally to social groups and parties, we can re-write it as follows:

$$
Pr(Party_j | Group_i) - Pr(Party_j | \mathord{\sim}Group_i)
$$ {#eq-alford2}

To calculate the ICV, we simply need to define which parties are left-wing and which are not, and collect information on the voting behaviour of workers and non-workers. One strength of the Alford index is that it can be calculated over long periods of time and across countries. Another is that it fits well with the way political scientists analyse voting behaviour. We often look for the factors that influence voting for a party or family of parties and then calculate the probability of voting for party *j* for group *i*. For example, studies have looked at the likelihood of voting for the radical right among women and men, age and education groups, or indeed social classes. The ICV is an effective way of describing the behavioural differences between these groups.

@Hooghe.2025[: 18] provide the following example from two German elections:

|                      | 1957  | 2017  |
|:------------------   |:------|:------|
| % workers in society | 47.4  | 14.7  |
| % workers voted SPD  | 34.3  | 29.0  |
| % of SPD in election | 21.7  | 25.6  |
| ICV                  | 23.9  | 3.99  |
: Workers and SPD vote share in Germany, 1957 and 2017. {#tbl-spd}

To get the ICV, we have to compute the share of non-workers who voted for the SPD. 

$0.343 \times 0.474 + x \times 0.526 = 0.217$

$x \times 0.526 = 0.217 - 0.343 \times 0.474$

$x = (0.217 - 0.1625) / 0.526$ 

$x = 10.39$

While 34.3 per cent of workers voted for the SPD in 1957, only 10.4 per cent of non-workers did so. The Alford index is therefore around 24 per cent. If we do the same calculation for 2017, the ICV falls to 4 per cent, because 25 per cent of non-workers chose the Social Democrats in the latter election. The ICV thus shows that the SPD has lost support among workers but gained votes from other groups.^[Note, however, that the figures in @tbl-spd are based on surveys and include non-voters. The official SPD vote differs considerably from the figures given.] 

As shown in the previous section, we can express the conditional probability of voting Social Democrats for workers and non-workers using Bayes' rule, which means that we can re-write @eq-alford1 in the following way:

$$
ICV = \left(\frac{Pr(Worker | SPD) \times Pr(SPD)}{Pr(Worker)} \right) - \left(\frac{Pr(\mathord{\sim}Worker | SPD) \times Pr(SPD)}{Pr(\mathord{\sim}Worker)}\right)
$$ {#eq-icv_bayes}

To show that we arrive at the same result as before using this version, we turn the figures for the 1957 election in Germany into a joint probability table, in which the cells add up to one.^[We get the number in the upper left cell by multiplying the proportion of workers who voted for the SPD by the proportion of workers in society (0.343 * 0.474 = 0.1625).]

|          | SPD     | ~SPD   | sum    |
|:---------|:--------|:-------|:-------|
| Worker   | 0.163   | 0.311  | 0.474  |
| ~Worker  | 0.054   | 0.472  | 0.526  |
| sum      | 0.217   | 0.783  | 1      |
: Joint probability table for SPD vote in 1957. {#tbl-joint_spd}

The figures in @tbl-joint_spd show that roughly one third of the 47% workers in society opted for the SPD in 1957 but only one out of ten non-workers.^[Note, however, that "not SPD" includes all the other parties as well as nonvoters.] We now calculate the probability of workers voting for the SPD and subtract the probability of non-workers voting for the SPD if we plug in the number into @eq-icv_bayes and arrive---except for rouding errors---at the same result.

$$
ICV = \frac{\frac{0.163}{.0217} \times 0.217}{0.474} - \frac{\frac{0.054}{.0217} \times 0.217}{0.526} = 0.242
$$ {#eq-icv_bayes_spd}

## Axelrod's Contribution Index

In the next step I look at the second perspective on cleavages, which is the *contribution* of a group to a party's vote share. When Alford applied the ICV to GB, Australia, Canada and the United States, he focused on manual workers, who made up about 40 per cent of the population at the time [@Alford.1967: 74, Table 1]. In the two countries with high values of the ICV, Britain and Australia, this meant not only that workers were considerably more likely to vote for left parties, but also that the majority of voters for these parties were workers. However, @Alford.1967[: 80] fully acknowledges that his index does 'leave aside' the 'degree of class distinctiveness of the Left party (the proportion of support for the Left party drawn from workers)'---which is nothing other than the contribution.

In his article, Axelrod starts from the observation that neither practitioners nor scholars know much about the support coalitions of US parties. He is not primarily interested in how likely a group is to vote for one of the two parties, but in how much of the party's votes come from that group. He thus introduces the *Contribution Index* (ACI) to measure the contribution of different groups to the party vote in the US. Axelrod.1972[: 11] identifies three factors that determine a group's contribution to a party's vote: 'the size of the group, its turnout, and its loyalty to the given party.' Loyality is the likelihood of voting for a party in a given group. He suggests the following formula to calculate the contribution of group *j* to party *i*:

$$
Contribution_i = \frac{Loyalty_j \times Size_j}{Loyalty} \times \frac{Turnout_j}{Turnout}
$$ {#eq-ACI}

Again, we can express this formula using Bayes' rule because the contribution is the probability to belong to group *j* given that one votes for party *i* and loyalty is the likelihood to vote for party *i* given one is a member of group *j*:
$$
Pr(Group_j|Party_i) = \frac{Pr(Party_i | Group_j) \times Pr(Group_j)}{Pr(Party_i)} \times \frac{Pr(Turnout_j)}{Pr(Turnout)}
$$ {#eq-ACI_bayes}

If we use survey data to calculate the contribution, we can incorporate turnout to the measurement of loyalty and thus the latter part of @eq-ACI_bayes is not necessary and the equation has exactly the same structures as @eq-bayes2.

In the article, Axelrod provides data for a number of groups to caculate their contribution the the Democratic and Republican vote in several elections. @tbl-black shows the loyalty, turnout and size only of Black voters in 1952 and 1968 and focuses on the Democrats. The probability to vote for the Democrats is the product of turnout and loyalty.

|      | Loyalty | Turnout | Size | NT   | NL    | ACI   |
|------|---------|---------|------|------|-------|-------|
| 1952 | 0.83    | 0.23    | 0.10 | 0.63 | 0.444 | 0.068 |
| 1968 | 0.92    | 0.51    | 0.11 | 0.62 | 0.427 | 0.197 |
: Loyalty, turnout and group size of Black voters in US elections. {#tbl-black}

We can calculate the contribution of Black to the Democratic vote in 1952 using @eq-ACI_bayes:
$$
Pr(Black | Dem) = \frac{(0.83 \times 0.23) \times 0.1}{(0.444 \times 0.63)} = 0.068
$$ {#eq-ACI_bayes_black}

In 1952, Black voters---also due to their suppressed turnout---contributed only 6.8. per cent to the Democratic vote, despite the fact that their loyalty was high. In 1968, the contribution rose to 19.7 per cent because even higher loyalty and higher turnout after the Voting Rights Act of 1965. And, of course, we can use the contribution to calculate the probability of Blacks to vote for the Democrats in 1952 with @eq-bayes1, which is $Pr(Dem|Black) = 0.068 \times 0.444 \times 0.63 / 0.1 = 0.19$ or 19 per cent.

## Party Cleavage Index

In a recent article, @Hooghe.2025 introduce the *Party Cleavage Index* (PCI) as a measure of the relative size of different voter groups in a party's electorate. They build on an earlier article that developed a measure to calculate the 'social basis of parties' [@Marks.2023]. Without using the vocabulary, the authors use Bayes' rule to calculate the PCI. Whlie ICV is based on the probability of (manual) workers and non-workers to vote for the left, the PCI is---as Axelrod's contribution index---based on the 'inverse probability' of being a worker given that one voted for the left or, more generally, the probability of belonging to group _i_ given that one has voted party _j_. 

Thus, while the ICV calculates the proportion of workers who vote for a left-wing party and subtracts the proportion of non-workers who vote for a left-wing party [@Alford.1967: 80], the PCI asks: Given that a person votes for a party, what is the probability that this person is a worker? In a second step, this probability is then subtracted from the probability of being a worker to see if workers vote disproportionately for this party. This logic can be applied to any other social group and @Hooghe.2025 are most interested in the composition of GAL and TAN parties and focus on education groups.

At the heart of the PCI is the contribution of a group to a party's vote, from which the group size is subtracted. Since @Hooghe.2025 want to provide a general forumula that applies to different parties and different social groups, they use the following notation:

$$
PCI = P_{ij}^{S} = \frac{\pi_{ilj}^{S} \times \pi_{j}^{S}}{\pi_{jli}} - \pi_{j}^{S}
$$ {#eq-pci}

@eq-pci assesses the probability of belonging to group *j* with the characteristc *s* (which could for example be gender, education, class or religious denomination) given that one has voted for party *i*. To arrive at the contribution, the probability of voting for party *i* given that one belongs to group *j* with the characteristic *s* is multiplied by the probability to belong to the specific group in question. This product is then divided by the probability of voting for party *i* for any group (i.e. the overall vote share of the party). In other words, they divide the product of the group size and the group vote for a party by the party's overall share of the vote. In other words the PCI is the contribution of a group minus the group size.

As shown above, the *contribution* of a group to a party's vote is nothing but Bayes' rule. Let me re-write @eq-pci in the familiar form:

$$
PCI = Pr(Group_j | Party_i) - Pr(Group_j) =
$$ 
$$
 \frac{Pr(Party_i | Group_j) \times Pr(Group_j)}{Pr(Party_i)} - Pr(Group_j)
$$ {#eq-pci_bayes}
 
To return to the example in @tbl-joint_spd, we can use it to calculate the contribution of workers to the SPD vote in 1957.

$$
Pr(Worker | SPD) = \frac{\frac{0.1625}{0.474} \times 0.474}{0.217} = 0.749
$$

If we subtract the share of workers in society (0.474) from the contribution of workers to the SPD vote (0.749), we get the PCI for workers in 1957, which is 0.275. This corresponds to the result in Table 1 of @Hooghe.2025[: 18], except for rounding errors.

# From Bayes' rule to Bayesian estimation


# Literature